# Generated by Django 3.0.3 on 2020-03-28 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200224_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default=None, help_text='author', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(help_text='category', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.CharField(help_text='image url', max_length=200),
        ),
    ]
